# Put this file in ~/.config/helix/ and RENAME it to config.toml
# If yanking (copying) and pasting to and from system clipboard does not work, try installing xsel package.
# Check with "hx --health clipboard" that xsel is used.

theme = "dark_plus"

[editor]
true-color = true
color-modes = true
bufferline = "always"

# inline-diagnostics does not work with release 24.7 --> build from source to use
[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.lsp]
display-inlay-hints = true

[editor.auto-save]
"focus-lost" = true
"after-delay.enable" = true
"after-delay.timeout" = 3000

[keys.normal]
# C-f = ":sh zellij run --floating -n 'yazi picker' --height 80% --width 80% -x 10% -y 10% -- /home/ville/.config/helix/yazi_to_helix.sh"
"C-A-h" = ":toggle lsp.display-inlay-hints"
C-A-b = ":buffer-close"
C-f = ":sh zellij action focus-next-pane"
A-k= [ # scroll selections up one line
    "ensure_selections_forward",
    "extend_to_line_bounds",
    "extend_char_right",
    "extend_char_left",
    "delete_selection",
    "move_line_up",
    "add_newline_above",
    "move_line_up",
    "replace_with_yanked"
]

A-j = [ # scroll selections down one line
    "ensure_selections_forward",
    "extend_to_line_bounds",
    "extend_char_right",
    "extend_char_left",
    "delete_selection",
    "add_newline_below",
    "move_line_down",
    "replace_with_yanked"
]
